version: '3.8'
services:
  pitt_urc_jetson:
    image: urc_jetson
    container_name: pitt_urc_jetson
    runtime: nvidia
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY
    devices:
      # - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
      - "/dev/iio:device0:/dev/iio:device0"
    restart: unless-stopped
    stdin_open: true
    tty: true
