services:
  pitt_urc_jetson:
    image: urc_jetson
    container_name: pitt_urc_jetson
    runtime: nvidia
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LIBGL_ALWAYS_INDIRECT=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    devices:
      - /dev:/dev
    restart: unless-stopped
    stdin_open: true
    tty: true
