services:
  pitt_urc_jetson:
    image: urc_jetson
    container_name: pitt_urc_jetson
    runtime: nvidia
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev:/dev
    restart: unless-stopped
    stdin_open: true
    tty: true
