services:
  pitt_urc_local:
    image: urc_local
    container_name: pitt_urc_local
    stdin_open: true     # Equivalent to `-it`
    tty: true            # Keeps the container interactive
    restart: unless-stopped
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes: 
      - ./../../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
